/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view.UserAdminitrator;

import com.mycompany.model.Perfil;
import com.mycompany.model.PerfilJpaController;
import com.mycompany.model.Usuario;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author luana
 */
public class DataUserAdministratorPanel extends javax.swing.JPanel {
    
    private PerfilJpaController PerfilJPA;
    private List<Usuario> usuarioList;
    private Perfil perfil;

    /**
     * Creates new form DataUserAdministratorPanel
     */
    public DataUserAdministratorPanel() {
        initComponents();
    }
    
    public String getTextIdNumber(){
        return this.txtId.getText();
    }
    
    public String getUserName(){
        return this.txtUserName.getText();
    }
    
    
    public Usuario getUser(){
        Usuario usuario= new Usuario(Integer.valueOf(this.txtId.getText().trim()), this.txtLastName.getText(),  this.txtName.getText(),this.txtCarnet.getText(), this.txtPhone.getText(), this.txtPassword.getText(), this.txtUserName.getText(), this.txtMail.getText());
        usuarioList.add(usuario);
        perfil=(Perfil)this.cbProfileType.getSelectedItem();
        perfil.setUsuarioList(usuarioList);
        return usuario;
    }
    
    
    public void setUser(Usuario user){
        this.txtId.setText(user.getId().toString());
        this.txtLastName.setText(user.getApellido());
        this.txtName.setText(user.getNombre());
        this.txtCarnet.setText(user.getCarnet());
        this.txtPhone.setText(user.getTelefono());
        this.txtPassword.setText(user.getContrasena());
        this.txtUserName.setText(user.getNombreUsuario());
        this.txtMail.setText(user.getCorreo());
        this.cbProfileType.setSelectedItem(user.getPerfilList());
    }
    
    public void clean(){
        this.txtId.setText("");
        this.txtLastName.setText("");
        this.txtName.setText("");
        this.txtCarnet.setText("");
        this.txtPhone.setText("");
        this.txtPassword.setText("");
        this.txtUserName.setText("");
        this.txtMail.setText("");
        this.cbProfileType.setSelectedIndex(0);
    }
    
    public void listen(ActionListener controller){
        this.btnSearch.addActionListener(controller);
        this.cbProfileType.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtCarnet = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        cbProfileType = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 170, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 170, -1));
        add(txtCarnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 170, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 170, -1));
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 170, -1));
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 170, -1));
        add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 170, -1));
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 170, -1));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/7.png"))); // NOI18N
        btnSearch.setBorderPainted(false);
        btnSearch.setContentAreaFilled(false);
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 30, -1));

        cbProfileType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select type" }));
        add(cbProfileType, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 170, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Id");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Carnet");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Last name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Phone");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Password");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("User name");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Mail");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Profile type");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgrounds/5.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbProfileType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCarnet;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    public void setUser(Perfil userLoad) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
