/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view.CourseAdministrator;

import com.mycompany.model.Curso;
import java.awt.event.ActionListener;

/**
 *
 * @author luana
 */
public class DataCourseAdministratorPanel extends javax.swing.JPanel {

    /**
     * Creates new form DataCourseAdministratorPanel
     */
    public DataCourseAdministratorPanel() {
        initComponents();
    }
    
    public String getTextIdNumber(){
        return this.txtId.getText();
    }
    
    public Curso getCurso(){
        return new Curso(Integer.valueOf(this.txtId.getText().trim()), this.txtBlock.getText(), Integer.parseInt(this.txtWorkingHours.getText().trim()), Integer.parseInt(this.txtTeachingHours.getText().trim()), Integer.parseInt(this.txtCredits.getText().trim()), this.txtModality.getText(), this.txaDescription.getText(), this.txtName.getText());
    }
    
    public void setCurso(Curso curso){
        this.txtId.setText(curso.getSigla().toString());
        this.txtBlock.setText(curso.getBloque());
        this.txtCredits.setText(curso.getCantidadCreditos()+"");
        this.txtModality.setText(curso.getModalidad());
        this.txtName.setText(curso.getNombre());
        this.txtTeachingHours.setText(curso.getHorasLectivas()+"");
        this.txtWorkingHours.setText(curso.getHorasTrabajo()+"");
        this.txaDescription.setText(curso.getDescripcion());
    }
    
    public void clean(){
        this.txtId.setText("");
        this.txtBlock.setText("");
        this.txtCredits.setText("");
        this.txtModality.setText("");
        this.txtName.setText("");
        this.txtTeachingHours.setText("");
        this.txtWorkingHours.setText("");
        this.txaDescription.setText("");
    }
    
    
    public void listen(ActionListener controller){
        this.btnSearch.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearch = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtCredits = new javax.swing.JTextField();
        txtBlock = new javax.swing.JTextField();
        txtWorkingHours = new javax.swing.JTextField();
        txtTeachingHours = new javax.swing.JTextField();
        txtModality = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/7.png"))); // NOI18N
        btnSearch.setActionCommand("Search");
        btnSearch.setBorderPainted(false);
        btnSearch.setContentAreaFilled(false);
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 30, -1));
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 200, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 200, -1));
        add(txtCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 200, -1));
        add(txtBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 200, -1));
        add(txtWorkingHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 200, -1));
        add(txtTeachingHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 200, -1));
        add(txtModality, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 200, -1));

        txaDescription.setColumns(20);
        txaDescription.setRows(5);
        jScrollPane1.setViewportView(txaDescription);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 200, 90));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Acronym");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Block");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Working hours");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Teaching hours");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Number of credits");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Modality");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Description");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Name");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgrounds/1.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 440));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaDescription;
    private javax.swing.JTextField txtBlock;
    private javax.swing.JTextField txtCredits;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtModality;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTeachingHours;
    private javax.swing.JTextField txtWorkingHours;
    // End of variables declaration//GEN-END:variables
}
