/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view.PlanAdministrator;

import com.mycompany.model.CarreraJpaController;
import com.mycompany.model.PlanEstudios;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author luana
 */
public class DataPlanAdministratorPanel extends javax.swing.JPanel {
    
    private CarreraJpaController carreraJPA;

    /**
     * Creates new form DataPlanAdministratorPanel
     */
    public DataPlanAdministratorPanel() {
        initComponents();
        
        
    }
    
    public String getTextIdNumber(){
        return this.txtId.getText();
    }
    
    public PlanEstudios getPlanEstudios() throws ParseException{
        return new PlanEstudios(Integer.valueOf(this.txtId.getText().trim()), this.txaDescription.getText(), Integer.parseInt(this.txtNumberCredits.getText().trim()), this.getDate(this.txtApprovalDate.getText()), this.getDate(this.txtEffectiveDate.getText()), carreraJPA.findCarrera(this.cbSelecMajor.getSelectedItem().toString()));
    }
    
    public void setPlanEstudios(PlanEstudios plan){
        this.txtId.setText(plan.getId()+"");
        this.txaDescription.setText(plan.getDescripcion());
        this.txtNumberCredits.setText(plan.getCantidadCreditos()+"");
        this.txtApprovalDate.setText(plan.getFechaAprobacion().toString());
        this.txtEffectiveDate.setText(plan.getFechaVigor().toString());
        this.cbSelecMajor.setSelectedItem(plan.getCarreraCodigo());
        
    }
    
    //transforma un string en Date
    public Date getDate(String day) throws ParseException{
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date utilDate = formatter.parse(day);
        return utilDate;
    }
    
    
    
    public void clean(){
        this.txtId.setText("");
        this.txaDescription.setText("");
        this.txtNumberCredits.setText("");
        this.txtApprovalDate.setText("");
        this.txtEffectiveDate.setText("");
        this.cbSelecMajor.setSelectedIndex(0);
    }
    
    public void listen(ActionListener controller){
        this.btnSearch.addActionListener(controller);
        this.cbSelecMajor.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        txtApprovalDate = new javax.swing.JFormattedTextField();
        txtEffectiveDate = new javax.swing.JFormattedTextField();
        txtNumberCredits = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescription = new javax.swing.JTextArea();
        cbSelecMajor = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApprovalDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        add(txtApprovalDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 250, -1));

        txtEffectiveDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        add(txtEffectiveDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 250, -1));
        add(txtNumberCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 250, -1));
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 250, -1));

        txaDescription.setColumns(20);
        txaDescription.setRows(5);
        jScrollPane1.setViewportView(txaDescription);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 250, -1));

        cbSelecMajor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select major" }));
        add(cbSelecMajor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 250, -1));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/7.png"))); // NOI18N
        btnSearch.setActionCommand("Search");
        btnSearch.setBorderPainted(false);
        btnSearch.setContentAreaFilled(false);
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 30, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Major Code");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Id");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Description");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Number of credits");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Approval date");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Effective date");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgrounds/2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbSelecMajor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaDescription;
    private javax.swing.JFormattedTextField txtApprovalDate;
    private javax.swing.JFormattedTextField txtEffectiveDate;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNumberCredits;
    // End of variables declaration//GEN-END:variables
}
