/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view;

import java.awt.event.ActionListener;

/**
 *
 * @author luana
 */
public class ButtonsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ButtonsPanel
     */
    public ButtonsPanel() {
        initComponents();
    }
    
    public void listen(ActionListener controller){
        this.btnBack.addActionListener(controller);
        this.btnDelete.addActionListener(controller);
        this.btnEdit.addActionListener(controller);
        this.btnReport.addActionListener(controller);
        this.btnSave.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgrounds/4.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/4.png"))); // NOI18N
        btnSave.setActionCommand("Save");
        btnSave.setBorderPainted(false);
        btnSave.setContentAreaFilled(false);
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/3.png"))); // NOI18N
        btnEdit.setActionCommand("Edit");
        btnEdit.setBorderPainted(false);
        btnEdit.setContentAreaFilled(false);
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/6.png"))); // NOI18N
        btnReport.setActionCommand("Report");
        btnReport.setBorderPainted(false);
        btnReport.setContentAreaFilled(false);
        add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/5.png"))); // NOI18N
        btnDelete.setActionCommand("Delete");
        btnDelete.setBorderPainted(false);
        btnDelete.setContentAreaFilled(false);
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/2.png"))); // NOI18N
        btnBack.setActionCommand("Back");
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
