/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import java.awt.event.ActionListener;

/**
 *
 * @author luana
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void listen (ActionListener controller){
        this.miCourseAdministrator.addActionListener(controller);
        this.miCredits.addActionListener(controller);
        this.miExit.addActionListener(controller);
        this.miMajorAdministrator.addActionListener(controller);
        this.miPlanAdministrator.addActionListener(controller);
        this.miUserAdministrator.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbFile = new javax.swing.JMenu();
        miCredits = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();
        mbModules = new javax.swing.JMenu();
        miCourseAdministrator = new javax.swing.JMenuItem();
        miMajorAdministrator = new javax.swing.JMenuItem();
        miPlanAdministrator = new javax.swing.JMenuItem();
        miUserAdministrator = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgrounds/4.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 500, 260));

        mbFile.setText("File");

        miCredits.setText("Credits");
        mbFile.add(miCredits);

        miExit.setText("Exit");
        mbFile.add(miExit);

        jMenuBar1.add(mbFile);

        mbModules.setText("Modules");

        miCourseAdministrator.setText("Course Administrator");
        mbModules.add(miCourseAdministrator);

        miMajorAdministrator.setText("Major Administrator");
        mbModules.add(miMajorAdministrator);

        miPlanAdministrator.setText("Study Plan Administrator");
        mbModules.add(miPlanAdministrator);

        miUserAdministrator.setText("User Administrator");
        mbModules.add(miUserAdministrator);

        jMenuBar1.add(mbModules);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mbFile;
    private javax.swing.JMenu mbModules;
    private javax.swing.JMenuItem miCourseAdministrator;
    private javax.swing.JMenuItem miCredits;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miMajorAdministrator;
    private javax.swing.JMenuItem miPlanAdministrator;
    private javax.swing.JMenuItem miUserAdministrator;
    // End of variables declaration//GEN-END:variables
}
